In [2]:
import cv2 as cv
import numpy as np

In [2]:
# img_color = cv.imread('D:\\pyproject\\bittestenv\\notebook\\images\\test.png')
# img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
# ret, img_binary = cv.threshold(img_gray, 127, 255, 0)
# contours, hierarchy = cv.findContours(img_binary, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)

# cv.imshow('result', img_color)
# cv.waitKey(0)

# cv.destroyAllWindows()

In [4]:
# img_color = cv.imread('D:\\pyproject\\bittestenv\\notebook\\images\\test.png')
# img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
# ret, img_binary = cv.threshold(img_gray, 127, 255, 0)
# contours, hierarchy = cv.findContours(img_binary, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)

# cv.drawContours(img_color, contours, 0, (0, 255, 0), 3)
# cv.drawContours(img_color, contours, 1, (255, 0, 0), 3)

# cv.imshow('result', img_color)
# cv.waitKey(0)

# cv.destroyAllWindows()  

In [9]:
# img_color = cv.imread('D:\\pyproject\\bittestenv\\notebook\\images\\hierarchy.jpg')
# img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
# ret, img_binary = cv.threshold(img_gray, 127, 255, 0)
# contours, hierarchy = cv.findContours(img_binary, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)

# for cnt in contours:
#     for p in cnt:
#         cv.circle(img_color, (p[0][0], p[0][1]), 10, (255, 0, 0), -1)

# cv.imshow('result', img_color)
# cv.waitKey(0)

# cv.destroyAllWindows()  

In [17]:
img_color = cv.imread('D:\\pyproject\\bittestenv\\notebook\\images\\hierarchy.jpg')
img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
ret, img_binary = cv.threshold(img_gray, 127, 255, 0)
contours, hierarchy = cv.findContours(img_binary, cv.RETR_CCOMP, cv.CHAIN_APPROX_SIMPLE)

for cnt in contours:
    cv.drawContours(img_color, [cnt], 0, (255, 0, 0), 3)
    
print(hierarchy)

cv.imshow('result', img_color)
cv.waitKey(0)

cv.destroyAllWindows()  

[[[ 3 -1  1 -1]
  [ 2 -1 -1  0]
  [-1  1 -1  0]
  [ 5  0  4 -1]
  [-1 -1 -1  3]
  [ 7  3  6 -1]
  [-1 -1 -1  5]
  [ 8  5 -1 -1]
  [-1  7 -1 -1]]]


In [22]:
# 영역 크기

img_color = cv.imread('D:\\pyproject\\bittestenv\\notebook\\images\\test.png')
img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
ret, img_binary = cv.threshold(img_gray, 127, 255, 0)
contours, hierarchy = cv.findContours(img_binary, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)

for cnt in contours:
    cv.drawContours(img_color, [cnt], 0, (255, 0, 0), 3)
    


cv.imshow('result', img_color)
cv.waitKey(0)

for cnt in contours:
    area = cv.contourArea(cnt)
    print(area)
    
cv.imshow('result', img_color)
cv.waitKey(0)

cv.destroyAllWindows() 

18772.0
13426.0


In [25]:
# 근사화

img_color = cv.imread('D:\\pyproject\\bittestenv\\notebook\\images\\box.png')
img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
ret, img_binary = cv.threshold(img_gray, 127, 255, 0)
contours, hierarchy = cv.findContours(img_binary, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)

for cnt in contours:
    cv.drawContours(img_color, [cnt], 0, (255, 0, 0), 3)
    


cv.imshow('result', img_color)
cv.waitKey(0)

for cnt in contours:
    epsilon = 0.02 * cv.arcLength(cnt, True)
    approx = cv.approxPolyDP(cnt, epsilon, True)
    print(len(approx))
    
    cv.drawContours(img_color, [approx], 0, (0, 255, 255), 5)
    
cv.imshow('result', img_color)
cv.waitKey(0)

cv.destroyAllWindows() 

4


In [27]:
# 무게중심 

img_color = cv.imread('D:\\pyproject\\bittestenv\\notebook\\images\\test.png')
img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
ret, img_binary = cv.threshold(img_gray, 127, 255, 0)
contours, hierarchy = cv.findContours(img_binary, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)

for cnt in contours:
    cv.drawContours(img_color, [cnt], 0, (255, 0, 0), 3)
    


cv.imshow('result', img_color)
cv.waitKey(0)

for cnt in contours:
    M = cv.moments(cnt)
    
    cx = int(M['m10']/M['m00'])
    cy = int(M['m01']/M['m00'])
    
    cv.circle(img_color, (cx, cy), 10, (0, 0, 255), -1)
    
    
    
cv.imshow('result', img_color)
cv.waitKey(0)

cv.destroyAllWindows() 

In [3]:
# 경계 사각형

img_color = cv.imread('D:\\pyproject\\bittestenv\\notebook\\images\\test.png')
img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
ret, img_binary = cv.threshold(img_gray, 127, 255, 0)
contours, hierarchy = cv.findContours(img_binary, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)

for cnt in contours:
    cv.drawContours(img_color, [cnt], 0, (255, 0, 0), 3)
    


cv.imshow('result', img_color)
cv.waitKey(0)

for cnt in contours:
    x, y, w, h = cv.boundingRect(cnt)
    cv.rectangle(img_color, (x, y), (x + w, y + h), (0, 255, 0), 2)
    
cv.imshow('result', img_color)
cv.waitKey(0)

for cnt in contours:
    rect = cv.minAreaRect(cnt)
    box = cv.boxPoints(rect)
    box = np.int0(box)
    cv.drawContours(img_color, [box], 0, (0, 0, 255), 2)
    
cv.imshow('result', img_color)
cv.waitKey(0)

cv.destroyAllWindows() 

In [6]:
# convex hull

img_color = cv.imread('D:\\pyproject\\bittestenv\\notebook\\images\\hand.png')
img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
ret, img_binary = cv.threshold(img_gray, 127, 255, 0)
contours, hierarchy = cv.findContours(img_binary, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)

for cnt in contours:
    cv.drawContours(img_color, [cnt], 0, (255, 0, 0), 3)
    


cv.imshow('result', img_color)
cv.waitKey(0)

for cnt in contours:
    hull = cv.convexHull(cnt)
    cv.drawContours(img_color, [hull], 0, (255, 0, 255), 5)
  
    
cv.imshow('result', img_color)
cv.waitKey(0)

cv.destroyAllWindows() 

In [7]:
# convex defects

img_color = cv.imread('D:\\pyproject\\bittestenv\\notebook\\images\\hand.png')
img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
ret, img_binary = cv.threshold(img_gray, 127, 255, 0)
contours, hierarchy = cv.findContours(img_binary, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)

for cnt in contours:
    cv.drawContours(img_color, [cnt], 0, (255, 0, 0), 3)
    


cv.imshow('result', img_color)
cv.waitKey(0)

for cnt in contours:
    hull = cv.convexHull(cnt)
    cv.drawContours(img_color, [hull], 0, (255, 0, 255), 5)
  
    
cv.imshow('result', img_color)
cv.waitKey(0)

for cnt in contours:
    hull = cv.convexHull(cnt, returnPoints = False)
    defects = cv.convexityDefects(cnt, hull)
    
    for i in range(defects.shape[0]):
        s, e, f, d = defects[i,0]
        start = tuple(cnt[s][0])
        end = tuple(cnt[e][0])
        far = tuple(cnt[f][0])
        
        print(d)
        
        if d > 500:
            cv.line(img_color, start, end, [0, 255, 0], 5)
            cv.circle(img_color, far, 5, [0, 0, 255], -1)
            
        cv.imshow('result', img_color)
        cv.waitKey(0)

cv.destroyAllWindows() 

114
31505
142
114
162
38208
190
40643
160
33132
142
114
186
210
114
5377
169
1088
1267
